# -*- coding: UTF-8 -*-

# ------------------------(max to 80 columns)-----------------------------------
# author by : （学员ID)
# created:  2019.11

# Description:
#   初步学习 WinForm 编程 ( Window )
# ------------------------(max to 80 columns)-----------------------------------

import tkinter as tk
from tkinter import ttk
import tkinter.messagebox

# create root window
top_win = tk.Tk()

# naming root window
top_win.title('Hello World Window')

# resize root window
win_size_pos = '800x600'
#win_size_pos = '360x60'
top_win.geometry(win_size_pos)

#------------------------------
# balablabla
title = 'My Label Frame'
lfm_step1 = ttk.Labelframe(
            top_win, text=title, width=240, height=500)
#lfm_step1.place(x=20, y=20)
lfm_step1.grid(row=0, column=0, padx=10, pady=10)

lbl_test0 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test0.grid(row=0, column=0, pady=5, padx=5)
lbl_test1 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test1.grid(row=1, column=0, pady=5, padx=5)
lbl_test2 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test2.grid(row=2, column=0, pady=5, padx=5)
lbl_test3 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test3.grid(row=3, column=0, pady=5, padx=5)
lbl_test4 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test4.grid(row=4, column=0, pady=5, padx=5)

lbl_test0 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test0.grid(row=0, column=1, pady=5, padx=5)
lbl_test1 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test1.grid(row=1, column=1, pady=5, padx=5)
lbl_test2 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test2.grid(row=2, column=1, pady=5, padx=5)
lbl_test3 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test3.grid(row=3, column=1, pady=5, padx=5)
lbl_test4 = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test4.grid(row=4, column=1, pady=5, padx=5)

title = 'My Label Frame generated by for'
lfm_step2 = ttk.Labelframe(
            top_win, text=title, width=240, height=500)
#lfm_step2.place(x=400, y=20)
lfm_step2.grid(row=0, column=1, padx=10, pady=10)

for r in range(5):
    for c in range(3):
        ent_row = tk.Entry(lfm_step2, show=None, width=8, bg='red', fg='white')
        #ent_row.place(x=20, y=20)
        ent_row.grid(row=r, column=c, padx=5, pady=5)

#------------------------------


# show window and get into event loop
top_win.mainloop()
